networks:
  backend:
  frontend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "${PROJECT_NAME}-nginx"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      -  ..:/var/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php-8.1
      - redis
      - postgres
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
      SERVER_NAME: ${SERVER_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
      PUBLIC_PATH: ${PUBLIC_PATH}
    networks:
      - backend
    extra_hosts:
      - '${SERVER_NAME}:${LOCAL_IP}'

  redis:
    image: redis:latest
    container_name: "${PROJECT_NAME}-redis"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  postgres:
    image: postgres:alpine
    container_name: "${PROJECT_NAME}-postgres"
    hostname: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
        - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: "${PROJECT_NAME}-pgadmin"
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MAX_LOGIN_ATTEMPTS: 50
    depends_on:
      - postgres
    links:
      - postgres
    extra_hosts:
      - 'pgadmin.localhost:${LOCAL_IP}'

  php-8.1:
    build:
      context: ./../
      dockerfile: ./docker-php/php/Dockerfile
      args:
        DOCKER_PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
        PUID: ${USER_UID}
        PGID: ${USER_GID}
    container_name: "${PROJECT_NAME}-php-8.1"
    working_dir: /var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./../:/var/www/
      - ./.ssh:/home/www-data/.ssh
      - ./php/ini/8.1/php.ini:/usr/local/etc/php/php.ini
      - ./php/workers/8.1/supervisor.d:/etc/supervisor.d
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - backend
